CREATE DATABASE yii2_test WITH OWNER = docker ENCODING = 'UTF8';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA webrtc_blocknerds;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA yii2_test;
